name: Deploy
on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: Deploy via scp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Upload to server via scp
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SCPHOST }}
          username: ${{ secrets.SCPUSERNAME }}
          port: ${{ secrets.SCPPORT }}
          key: ${{ secrets.SCPKEY }}
          source: "*,!.git*,!cv/.git*,!files/bibtexs/.git*"
          target: "rionda.to/"
