name: scp files
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SCPHOST }}
          username: ${{ secrets.SCPUSERNAME }}
          port: ${{ secrets.SCPPORT }}
          key: ${{ secrets.SCPKEY }}
          source: "!.git,!cv/.git"
          target: "rionda.to/"
