name: scp files
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SCPHOST }}
          username: ${{ secrets.SCPUSERNAME }}
          port: ${{ secrets.SCPPORT }}
          key: ${{ secrets.SCPKEY }}
          source: "*,!.git*,!cv/.git*,!files/bibtexs/.git*"
          target: "rionda.to/"
